name: Production deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /home/sauron/pizza
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: sauron
        remote_key: ${{ secrets.DEPLOY_KEY }}
